BEGIN;

DROP TABLE IF EXISTS "movie_category", "user", "movie_and_serie", "recipe_category", "recipe", "ingredient", "recipe_has_ingredient", "movie_has_category";

CREATE TABLE "movie_category" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR NOT NULL UNIQUE
);

CREATE TABLE "user" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "email" VARCHAR NOT NULL UNIQUE,
    "pseudo" VARCHAR NOT NULL UNIQUE,
    "password" VARCHAR NOT NULL,
    "avatar" VARCHAR,
    "role"  VARCHAR NOT NULL
);

CREATE TABLE "movie_and_serie" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR NOT NULL,
    "synopsis" VARCHAR NOT NULL,
    "director" VARCHAR NOT NULL,
    "actor" VARCHAR NOT NULL,
    "release_date" DATE NOT NULL,
    "picture" VARCHAR
);

CREATE TABLE "recipe_category" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR NOT NULL UNIQUE
);

CREATE TABLE "recipe" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR NOT NULL,
    "description" TEXT NOT NULL,
    "picture" VARCHAR,
    "difficulty" VARCHAR NOT NULL,
    "time" INTERVAL, 
    "instruction" TEXT NOT NULL,
    "recipe_category_id" INTEGER NOT NULL REFERENCES "recipe_category" ("id"),
    "movie_id" INTEGER NOT NULL REFERENCES "movie_and_serie" ("id"),
    "user_id" INTEGER NOT NULL REFERENCES "user" ("id")
);

CREATE TABLE "ingredient" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR NOT NULL,
    "picture" VARCHAR
);

CREATE TABLE "recipe_has_ingredient" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "recipe_id" INTEGER NOT NULL REFERENCES "recipe" ("id"),
    "ingredient_id" INTEGER NOT NULL REFERENCES "ingredient" ("id"),
    "quantity" INTEGER NOT NULL
);

CREATE TABLE "movie_has_category" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "movie_id" INTEGER NOT NULL REFERENCES "movie_and_serie" ("id"),
    "movie_category_id" INTEGER NOT NULL REFERENCES "movie_category" ("id")
);

COMMIT;